### ISSUE TITLE
"measurement_class.h" missing from the repo

### ISSUE THREAD

**Issue by AlexandreChern** [senior-zero/matrix_format_performance#1]
I am interested in this work, but "measurement_class.h" from the gpu_generated_scoo_spmv.cu file is missing from the repo. I couldn't find this header file online. Can you include this in the repo so I could try reproducing your results?

**Comment by gevtushenko** [comment]
Hello @AlexandreChern! Thank you for your interest in the work. 

Isn't [this](https://github.com/senior-zero/matrix_format_performance/blob/master/common/measurement_class.h) the file you are looking for?

**Comment by AlexandreChern** [comment]
Oh, thanks for pointing out that! I must forget to include the common subdirectory in the path. My bad
